version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: vivirootpassword
      MYSQL_DATABASE: vt402filrouge
      MYSQL_USER: user
      MYSQL_PASSWORD: vivi_user
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot_backend
    depends_on:
      - mysql
    ports:
      - "8282:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/vt402filrouge?createDatabaseIfNotExist=true&useSSL=true
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: vivi_user
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
